[assembly: System.Reflection.AssemblyCompanyAttribute("Innovabit.DotNet.Api.RestCountries")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Innovabit.DotNet.Api.RestCountries")]
[assembly: System.Reflection.AssemblyTitleAttribute("Innovabit.DotNet.Api.RestCountries")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Innovabit.DotNet.Api.RestCountries.Tests")]