name: Commit

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Set up .Net Core
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
      
      - name: Install dependencies
        run: dotnet restore

      - name: Execute tests
        run: dotnet test --no-restore